
name: touge_light
description: Touge Light - A Flutter app to control LED over BLE.

# The version number is composed of three parts: major.minor.patch+build_number
# The build name consists of three numbers separated by dots (major.minor.patch)
# The build number is a separate number after the + sign
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.2
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
